const ITEMS_PER_PAGE = 1;
const EVENTS_PER_PAGE = 5;

const ARTISTS_SEARCH = 'artists';
const LOCATIONS_SEARCH = 'location';

export { ITEMS_PER_PAGE, EVENTS_PER_PAGE, ARTISTS_SEARCH, LOCATIONS_SEARCH };
